### ISSUE TITLE
Some examples help us to use your precious library

### ISSUE THREAD

**Issue by ghost** [Mrtenz/soundfont2#1]
Hi，Would you please give us some samples to help us to work with your library?

**Comment by Mrtenz** [comment]
Thank you for your interest in the library. Since this library is very new (I've been working on it for about a week now), I didn't have the time to write extensive documentation yet. I'm also working on a synthesizer library that makes use of this library and the Web Audio API. When that is done, I'll work on proper documentation and better examples.

For now, there is a very quick example in the `README.md` and for anything else, you can look through the source code. I will keep this issue open as a reminder that I need to work on documentation. If you have any questions, feel free to ask me here.

Also, quick note that this library will have breaking changes with newer versions. As mentioned in the `README.md` it's not ready for production yet.

**Comment by ghost** [comment]
@Mrtenz Thank you so much! I would love to contribute a bit!

**Comment by Mrtenz** [comment]
I just published some basic documentation, to help you use this library. You can find it [here](https://mrtenz.github.io/soundfont2/). If you have any suggestions or improvements, feel free to open another issue.
